-- Create a table for contact messages
create table contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null,
  is_read boolean default false
);

-- Enable Row Level Security (RLS)
alter table contact_messages enable row level security;

-- Create specific policies
-- 1. Allow anyone (anon) to insert messages
create policy "Anyone can insert messages"
  on contact_messages for insert
  with check (true);

-- 2. Allow authenticated users (admin) to view messages
create policy "Authenticated users can view messages"
  on contact_messages for select
  using (auth.role() = 'authenticated');
